// src/lib/contracts/recurringPaymentERC20Abi.ts

export const recurringPaymentERC20Abi = [
  {
    inputs: [],
    name: 'payer',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'payee',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'tokenAddress',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'monthlyAmount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'protocolFeePerMonth',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'startDate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalMonths',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'dayOfMonth',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'executedMonths',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancelled',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'uint256' }],
    name: 'monthExecuted',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextMonthToProcess',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancel',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPaymentDetails',
    outputs: [
      { name: '_payer', type: 'address' },
      { name: '_payee', type: 'address' },
      { name: '_tokenAddress', type: 'address' },
      { name: '_monthlyAmount', type: 'uint256' },
      { name: '_protocolFeePerMonth', type: 'uint256' },
      { name: '_startDate', type: 'uint256' },
      { name: '_totalMonths', type: 'uint256' },
      { name: '_dayOfMonth', type: 'uint256' },
      { name: '_executedMonths', type: 'uint256' },
      { name: '_cancelled', type: 'bool' },
      { name: '_nextPaymentDate', type: 'uint256' },
      { name: '_canExecute', type: 'bool' },
      { name: '_isCompleted', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getStatus',
    outputs: [
      { name: 'status', type: 'string' },
      { name: 'monthsExecuted', type: 'uint256' },
      { name: 'monthsRemaining', type: 'uint256' },
      { name: 'amountPaid', type: 'uint256' },
      { name: 'monthsFailed', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: true, name: 'payee', type: 'address' },
      { indexed: true, name: 'tokenAddress', type: 'address' },
      { indexed: false, name: 'monthlyAmount', type: 'uint256' },
      { indexed: false, name: 'protocolFeePerMonth', type: 'uint256' },
      { indexed: false, name: 'startDate', type: 'uint256' },
      { indexed: false, name: 'totalMonths', type: 'uint256' },
      { indexed: false, name: 'dayOfMonth', type: 'uint256' },
    ],
    name: 'RecurringPaymentCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: false, name: 'monthsExecuted', type: 'uint256' },
      { indexed: false, name: 'monthsRemaining', type: 'uint256' },
    ],
    name: 'RecurringPaymentCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'monthNumber', type: 'uint256' },
      { indexed: true, name: 'payee', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'protocolFee', type: 'uint256' },
      { indexed: false, name: 'nextPaymentDate', type: 'uint256' },
    ],
    name: 'MonthlyPaymentExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'monthNumber', type: 'uint256' },
      { indexed: true, name: 'payer', type: 'address' },
      { indexed: false, name: 'reason', type: 'string' },
    ],
    name: 'MonthlyPaymentFailed',
    type: 'event',
  },
] as const;
